{"name": "test_1[1]", "status": "broken", "statusDetails": {"message": "ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。", "trace": "self = <Test.test_search.Test_Base object at 0x0467B070>\n\n    def setup(self):\n>       self.driver = init_driver()\n\nTest\\test_search.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nBasic\\Init_Driver.py:20: in init_driver\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\",desired_caps)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\appium_python_client-0.25-py3.6.egg\\appium\\webdriver\\webdriver.py:36: in __init__\n    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:91: in __init__\n    self.start_session(desired_capabilities, browser_profile)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:173: in start_session\n    'desiredCapabilities': desired_capabilities,\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:231: in execute\n    response = self.command_executor.execute(driver_command, params)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:395: in execute\n    return self._request(command_info[0], url, body=data)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:463: in _request\n    resp = opener.open(request, timeout=self._timeout)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\urllib\\request.py:526: in open\n    response = self._open(req, data)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\urllib\\request.py:544: in _open\n    '_open', req)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\urllib\\request.py:504: in _call_chain\n    result = func(*args)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\urllib\\request.py:1346: in http_open\n    return self.do_open(http.client.HTTPConnection, req)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\urllib\\request.py:1321: in do_open\n    r = h.getresponse()\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\http\\client.py:1331: in getresponse\n    response.begin()\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\http\\client.py:297: in begin\n    version, status, reason = self._read_status()\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\http\\client.py:258: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <socket.SocketIO object at 0x0465DFB0>, b = <memory at 0x045E53D8>\n\n    def readinto(self, b):\n        \"\"\"Read up to len(b) bytes into the writable buffer *b* and return\n        the number of bytes read.  If the socket is non-blocking and no bytes\n        are available, None is returned.\n    \n        If *b* is non-empty, a 0 return value indicates that the connection\n        was shutdown at the other end.\n        \"\"\"\n        self._checkClosed()\n        self._checkReadable()\n        if self._timeout_occurred:\n            raise OSError(\"cannot read from timed out object\")\n        while True:\n            try:\n>               return self._sock.recv_into(b)\nE               ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。\n\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\socket.py:586: ConnectionResetError"}, "parameters": [{"name": "a", "value": "1"}], "start": 1572965695824, "stop": 1572965695824, "uuid": "5ffaf32f-4964-4e84-bbf3-4aca6a89f275", "historyId": "e4de93357fd955bf569d6f0464a2687e", "testCaseId": "cbffb8fa9430b001aae176614c563687", "fullName": "Test.test_search.Test_Base#test_1", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "Test"}, {"name": "suite", "value": "test_search"}, {"name": "subSuite", "value": "Test_Base"}, {"name": "host", "value": "DESKTOP-E3BR8K0"}, {"name": "thread", "value": "5584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test.test_search"}]}